### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Rsatan** [notnotype/xxt#1]
dalao
报错
AttributeError: 'NoneType' object has no attribute 'group'
怎么解决？

**Comment by notnotype** [comment]
# 逻辑没问题, 应该是学习通api变化(错误), 导致无法获得改测试的题目
### 考试api地址 [https://exm-mayuan-ans.chaoxing.com/selftest/start-test?courseId=215779000&classId=1718&cpi=154457568&dirid=68773828&reset=true&protocol_v=1](https://exm-mayuan-ans.chaoxing.com/selftest/start-test?courseId=215779000&classId=1718&cpi=154457568&dirid=68773828&reset=true&protocol_v=1)显示 `当前题库目录下面无题目，无法自测。`
暂时不会修复
你可以自己抓包修复

**Comment by notnotype** [comment]
上传离线网页缓存, 提供脚本运行演示: fc1410bd9788231d7ddf2624eefa2b446b23ed8d
