### ISSUE TITLE
不能爬取完整的题库

### ISSUE THREAD

**Issue by Justin666521** [notnotype/xxt#11]
你读取题目的程序有问题，比如我题库有100题，你这个只能读取50题，因为它读取题目的时候读一个跳一个，
例如，读第一个，不读第二个，读第三个，应该是读题目步长错了，你看看怎么修改吧，谢谢爸爸！

**Comment by notnotype** [comment]
有没有证据？

**Comment by Justin666521** [comment]
有，我每次爬虫的结果就是证据

**Comment by notnotype** [comment]
你题库有多少题目，然后发一下log

**Comment by Justin666521** [comment]
![image](https://user-images.githubusercontent.com/82272061/174548075-41d86d81-4349-486f-b99e-2bb1cb26ba24.png)
![$A$HAL J~TQW7X)GB V2769](https://user-images.githubusercontent.com/82272061/174548195-f97dc350-eb76-4259-a6a2-e62f7fd4e27c.jpg)
你看，正好一半，它读一个跳一个

**Comment by Justin666521** [comment]
1147个题，读了573个

**Comment by notnotype** [comment]
学院id（fid/school_id）是多少

**Comment by Justin666521** [comment]
"fid":46514
而且好像只读偶数题

**Comment by notnotype** [comment]
是否通过手机查看题目数的？

**Comment by notnotype** [comment]
用于爬取的账号是否与用于查看题目数的账号一致？

**Comment by Justin666521** [comment]
> 是否通过手机查看题目数的？

用手机查看的题目数

**Comment by Justin666521** [comment]
> 用于爬取的账号是否与用于查看题目数的账号一致？

一致

**Comment by notnotype** [comment]
这个页面和你手机上看的一致？
https://exm-mayuan-ans.chaoxing.com/selftest/courses?fid=46514

**Comment by Justin666521** [comment]
> 这个页面和你手机上看的一致？ https://exm-mayuan-ans.chaoxing.com/selftest/courses?fid=46514

一致

**Comment by notnotype** [comment]
题目数是多少？

**Comment by Justin666521** [comment]
![image](https://user-images.githubusercontent.com/82272061/174553120-1f17fa5e-3211-4590-a8d4-0b95ec3e0d12.png)
坏了，电脑版的打开题目就成了一半了，我该怎么办才能把手机的fid查出来

**Comment by notnotype** [comment]
手机重新登录再看看题目数

**Comment by Justin666521** [comment]
![image](https://user-images.githubusercontent.com/82272061/174553513-33af643d-8f4e-4ddf-85ee-daddf4b62b12.png)
手机就是1000多道

**Comment by Justin666521** [comment]
电脑就是500多，离谱了

**Comment by notnotype** [comment]
手机重新登录再看看题目数

**Comment by Justin666521** [comment]
重新登录还是1000多

**Comment by notnotype** [comment]
我尝试登录一下你的手机端行吗？

**Comment by Justin666521** [comment]
我用Gmail发给你个账号吧

**Comment by notnotype** [comment]
经检测：自测所使用的fid(31421)与获取的学院id(46514)不一致，正确的course_id为212958051
使用正确的course_id重新运行程序即可

```
请输入课程id(course_id): 212958051
```

### 原因

可能本学院的自测页面使用了来自其他学院的自测

可能属于罕见现象

**Comment by Justin666521** [comment]
谢谢爸爸！！！！好羡慕你的技术，向你学习，你就是我的榜样！！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月20日(周一) 下午4:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [notnotype/xxt] 我终于发现问题了！！ (Issue #11)




 
经检测：自测所使用的fid(31421)与获取的学院id(46514)不一致，正确的course_id为212958051
 使用正确的course_id重新运行程序即可
 
原因
 
可能本学院的自测页面使用了来自其他学院的自测
