### ISSUE TITLE
课程id

### ISSUE THREAD

**Issue by xdcabc** [notnotype/xxt#13]

**Comment by xdcabc** [comment]
你好，我的课程id列表只有学院id，没有课程id

**Comment by notnotype** [comment]
截图

**Comment by xdcabc** [comment]
> 

![image](https://user-images.githubusercontent.com/41458224/174612319-90fe1260-359f-424b-9ed6-20ab0a785097.png)

**Comment by notnotype** [comment]
course_id就是

**Comment by xdcabc** [comment]
> course_id就是

![image](https://user-images.githubusercontent.com/41458224/174612545-e5e0d767-74e6-490c-b293-bff94c91884a.png)
我尝试过学习通课程页面的这个，好像不起作用

**Comment by xdcabc** [comment]
> course_id就是

![image](https://user-images.githubusercontent.com/41458224/174612754-2853e4c2-715b-4bfa-be8f-94c3f59a55d7.png)

**Comment by notnotype** [comment]
你确定输入了进去？

**Comment by xdcabc** [comment]
> 你确定输入了进去？

是的，我确定

**Comment by xdcabc** [comment]
> 你确定输入了进去？

IndexError: list index out of range
索引错误：列表索引超出范围？

**Comment by notnotype** [comment]
你这截图好像显示你没有输入course_id

**Comment by xdcabc** [comment]
我输入了，但是报错把它填了

**Comment by notnotype** [comment]
```python
xxt.crawl_course(input('请输入课程id(course_id): '))
```

改成

```python
xxt.crawl_course('<course_id>')
```

用你的课程id替换<course_id>试试

**Comment by xdcabc** [comment]
> ```python
> xxt.crawl_course(input('请输入课程id(course_id): '))
> ```
> 
> 改成
> 
> ```python
> xxt.crawl_course('<course_id>')
> ```
> 
> 用你的课程id替换<course_id>试试

![image](https://user-images.githubusercontent.com/41458224/174614517-83a52a4f-ef31-4b5e-a7fa-b85ddd08dff4.png)
他还是一样

**Comment by notnotype** [comment]
你没有改啊

**Comment by xdcabc** [comment]
> ```python
> xxt.crawl_course('<course_id>')
> ```

好吧我发错了，下面这个才是改了的
![image](https://user-images.githubusercontent.com/41458224/174614964-0bebc7dd-a841-4673-9843-549a1a8deb0f.png)

**Comment by xdcabc** [comment]
> 你没有改啊

不用输入id直接结束了

**Comment by notnotype** [comment]
用你的课程id替换<course_id>

**Comment by xdcabc** [comment]
> 用你的课程id替换<course_id>

![image](https://user-images.githubusercontent.com/41458224/174615406-c7b984df-dde0-4d04-817d-41378fbf5ad2.png)
hai还是一样

**Comment by xdcabc** [comment]
![image](https://user-images.githubusercontent.com/41458224/174615588-fe516e0c-516a-42af-a842-df6964b1989a.png)
huibuh会不会是这的问题呢？

**Comment by notnotype** [comment]
你course_id要填你自己的，你填了个啥

**Comment by xdcabc** [comment]
> 你course_id要填你自己的，你填了个啥

啊我填了课程id，，，

**Comment by notnotype** [comment]
![image](https://user-images.githubusercontent.com/41458224/174612319-90fe1260-359f-424b-9ed6-20ab0a785097.png)

填这张图里面的course_id

**Comment by xdcabc** [comment]
但是我的课不在这里面

**Comment by xdcabc** [comment]
是2342学校里的课程

**Comment by notnotype** [comment]
https://exm-mayuan-ans.chaoxing.com/selftest/mode?courseId=222958096
当前课程不允许自测

**Comment by xdcabc** [comment]
那么还能爬取吗？

**Comment by notnotype** [comment]
不能

**Comment by xdcabc** [comment]
好吧，谢谢你的帮助
