### ISSUE TITLE
为什么无论登陆哪个账号 查询到的课程都是这几个

### ISSUE THREAD

**Issue by 2682856025** [notnotype/xxt#15]
<img width="547" alt="截屏2022-12-04 下午9 12 08" src="https://user-images.githubusercontent.com/106012957/205492516-61184ceb-e98e-4b71-9ad9-9c05ca682fe8.png">
这是什么原因呀 大佬 
然后还有个debug
<img width="965" alt="截屏2022-12-04 下午9 13 21" src="https://user-images.githubusercontent.com/106012957/205492551-c5772e09-474e-4960-abd9-cd6f4547e244.png">

**Comment by notnotype** [comment]
因为你的学院只开设了这几门课

**Comment by 2682856025** [comment]
不是的 是我换了我五个同学的账号 不同学校的 全是这六门课 而且顺序一样

**Comment by notnotype** [comment]
可能是因为他们都是开设的这六门课

**Comment by 2682856025** [comment]
怎么可能 正在学的有很多课

**Comment by 2682856025** [comment]
<img width="663" alt="截屏2022-12-05 上午9 25 22" src="https://user-images.githubusercontent.com/106012957/205529543-71ec98ea-0cad-4c6b-980c-1b81d4e7cdbb.png">
这是其他账号 别的学校的 学的课程还有职业生涯规划等其他课程 查到的只有这几个

**Comment by notnotype** [comment]
是否学生自测界面只有这么些课程

**Comment by 2682856025** [comment]
<img width="1113" alt="截屏2022-12-05 上午9 40 08" src="https://user-images.githubusercontent.com/106012957/205530857-956a63f7-2da4-40b0-89a4-cf68fbad5ca4.png">
还有这么多课程

**Comment by notnotype** [comment]
你要看的是学生自测页面，只有学生自测页面有的才能识别

**Comment by 2682856025** [comment]
自测页面是指哪个

**Comment by notnotype** [comment]
https://github.com/notnotype/xxt/blob/main/imgs/1.png

**Comment by 2682856025** [comment]
这个页面电脑上是没有吗

**Comment by notnotype** [comment]
对
