### ISSUE TITLE
get_test_ids还是404，我也看不太懂，请教

### ISSUE THREAD

**Issue by Aluminum13** [notnotype/xxt#4]
Traceback (most recent call last):
  File "C:\Users\84728\xxt\main.py", line 143, in <module>
    _dir_ids = xxt.get_test_ids()
  File "C:\Users\84728\xxt\main.py", line 122, in get_test_ids
    resp.raise_for_status()
  File "C:\Users\84728\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url: http://passport2.chaoxing.com/login?refer=https%3A%2F%2Fexm-mayuan-ans.chaoxing.com%2Fselftest%2Fchapter-test%3FcourseId%3D212958051%26classId%3D5093%26cpi%3D92074510&fid=28948

**Comment by notnotype** [comment]
能把完整的错误报告发出来吗?

**Comment by notnotype** [comment]
是否已经更新到最新版本?

**Comment by Aluminum13** [comment]
我刚刚尝试了样例没有问题，但是在换成自己课程以后有问题，xxt = XXT('212958051', '5093', '92074510')，编译环境pycharm
Traceback (most recent call last):
&nbsp; File "<input&gt;", line 1, in <module&gt;
&nbsp; File "D:\PyCharm Community Edition 2021.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
&nbsp; &nbsp; pydev_imports.execfile(filename, global_vars, local_vars)&nbsp; # execute the script
&nbsp; File "D:\PyCharm Community Edition 2021.1.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
&nbsp; &nbsp; exec(compile(contents+"\n", file, 'exec'), glob, loc)
&nbsp; File "C:/Users/84728/xxt/main.py", line 143, in <module&gt;
&nbsp; &nbsp; _dir_ids = xxt.get_test_ids()
&nbsp; File "C:/Users/84728/xxt/main.py", line 122, in get_test_ids
&nbsp; &nbsp; resp.raise_for_status()
&nbsp; File "C:\Users\84728\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
&nbsp; &nbsp; raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:&nbsp; for url: http://passport2.chaoxing.com/login?refer=https%3A%2F%2Fexm-mayuan-ans.chaoxing.com%2Fselftest%2Fchapter-test%3FcourseId%3D212958051%26classId%3D5093%26cpi%3D92074510&amp;fid=28948







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月30日(星期四) 下午4:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [notnotype/xxt] get_test_ids还是404，我也看不太懂，请教 (Issue #4)





 
能把完整的错误报告发出来吗?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aluminum13** [comment]
爬虫本身我刚刚重新clone的，库也重新安装了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月30日(星期四) 下午4:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [notnotype/xxt] get_test_ids还是404，我也看不太懂，请教 (Issue #4)





 
是否已经更新到最新版本?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by notnotype** [comment]
cookies换了没

**Comment by Aluminum13** [comment]
啊，没有，请问怎么换呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "notnotype/xxt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 下午4:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [notnotype/xxt] get_test_ids还是404，我也看不太懂，请教 (Issue #4)





 
cookies换了没
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by notnotype** [comment]
登录后把新cookies填到这里
[set_cookies](https://github.com/notnotype/xxt/blob/6076573c57f3bf9b257da86345987888e8a60088/main.py#L140)

**Comment by Aluminum13** [comment]
请问有办法可以快速导出cookies吗（一个一个查然后改好累




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "notnotype/xxt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [notnotype/xxt] get_test_ids还是404，我也看不太懂，请教 (Issue #4)





 
登录后把新cookies填到这里
 set_cookies
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by notnotype** [comment]
![image](https://user-images.githubusercontent.com/53962334/147735169-25979584-3c40-492f-b78f-1ef757fd7733.png)
把这一段复制过来就行了

**Comment by Aluminum13** [comment]
啊，我是在application里面一个个查的……谢谢，我的问题解决了，第一次用好多不会，再次谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "notnotype/xxt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 下午4:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [notnotype/xxt] get_test_ids还是404，我也看不太懂，请教 (Issue #4)





 

 把这一段复制过来就行了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by notnotype** [comment]
😊
