### ISSUE TITLE
程序一直调试不好，能给个联系方式吗，想问些问题（跪求）

### ISSUE THREAD

**Issue by Justin666521** [notnotype/xxt#8]
程序一直调试不好，能给个联系方式吗，想问些问题（跪求）

**Comment by notnotype** [comment]
有问题就在这里问

**Comment by Justin666521** [comment]
# _dir_ids = [68773748] 这个参数从哪里找，没搞明白

**Comment by Sheldon43557** [comment]
我实在运行不通。。。。我把参数给你你帮我运行一下行吗？


***@***.***
 
发件人： Notype
发送时间： 2022-06-17 20:13
收件人： notnotype/xxt
抄送： Jackson_coder; Author
主题： Re: [notnotype/xxt] 程序一直调试不好，能给个联系方式吗，想问些问题（跪求） (Issue #8)
有问题就在这里问

**Comment by notnotype** [comment]
这个参赛不需要，只需要readme里面说的三个参赛就行了

**Comment by Justin666521** [comment]
一共1147个题，爬虫只爬取了477个题，该怎么解决？

**Comment by notnotype** [comment]
设置cookies

**Comment by Justin666521** [comment]
, line 67, in set_cookie
    k, v = cookie.strip().split('=')
ValueError: too many values to unpack (expected 2)
总是报这个错
我弄不清楚怎么设置cookie,能详细说说吗

**Comment by Justin666521** [comment]
哥，能给个联系方式不，在这上面对话完全不能及时回复，效率太低了，求求了

**Comment by notnotype** [comment]
你填的是什么

**Comment by Justin666521** [comment]
就把cookie复制进去了，可能我的cookie找错了？你能在readme里说明一下你这个cookie参数从哪个网页哪个地方找的吗？

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月19日(周日) 中午11:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [notnotype/xxt] 程序一直调试不好，能给个联系方式吗，想问些问题（跪求） (Issue #8)




 
你填的是什么

**Comment by notnotype** [comment]
登录后，请求头里面的cookies字段

**Comment by Justin666521** [comment]
我就是这么搞的，但是就是报错，我可以肯定是cookie不对，但我不知道怎么弄到对的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月19日(周日) 中午12:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [notnotype/xxt] 程序一直调试不好，能给个联系方式吗，想问些问题（跪求） (Issue #8)




 
登录后，请求头里面的cookies字段

**Comment by Justin666521** [comment]
line 67, in set_cookie
    k, v = cookie.strip().split('=')
ValueError: too many values to unpack (expected 2)

**Comment by Justin666521** [comment]
line 67, in set_cookie
    k, v = cookie.strip().split('=')
ValueError: too many values to unpack (expected 2)

**Comment by Justin666521** [comment]
line 67, in set_cookie
    k, v = cookie.strip().split('=')
ValueError: too many values to unpack (expected 2)

**Comment by Justin666521** [comment]
line 67, in set_cookie
    k, v = cookie.strip().split('=')
ValueError: too many values to unpack (expected 2)

**Comment by Justin666521** [comment]
line 67, in set_cookie
    k, v = cookie.strip().split('=')
ValueError: too many values to unpack (expected 2)

**Comment by Justin666521** [comment]
我的cookie值里面有等号，所以报上面的错，我该怎么处理这个问题

**Comment by notnotype** [comment]
cookies里面本来就要有等号

**Comment by Justin666521** [comment]
我是说在值里面有等号，不是正常的等号



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月19日(周日) 下午3:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [notnotype/xxt] 程序一直调试不好，能给个联系方式吗，想问些问题（跪求） (Issue #8)




 
cookies里面本来就要有等号

**Comment by notnotype** [comment]
发出来看看

**Comment by Justin666521** [comment]
这是可以发的吗？

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月19日(周日) 下午3:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [notnotype/xxt] 程序一直调试不好，能给个联系方式吗，想问些问题（跪求） (Issue #8)




 
发出来看看
